import org.gradle.internal.os.OperatingSystem
import java.io.File

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.serialization)
    alias(libs.plugins.parcelize)
    alias(libs.plugins.kapt)
    id("app.fileseeker.convention.library")
}

android {
    namespace = "app.atomofiron.fileseeker"

    defaultConfig {
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation(libs.kotlinx.core)
    implementation(libs.kotlinx.core.android)
    implementation(libs.kotlinx.protobuf)
    api(libs.androidx.appcompat)
    api(libs.androidx.datastore)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.lifecycle)
    implementation(libs.androidx.lifecycle.ktx)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.work)
    implementation(libs.androidx.navigation.fragment)
    implementation(libs.androidx.navigation.ui)
    implementation(libs.androidx.flexbox)
    implementation(libs.androidx.exif)
    implementation(libs.androidx.async.inflater)
    implementation(libs.androidx.room)
    ksp(libs.androidx.room.compiler)
    implementation(libs.dagger)
    kapt(libs.dagger.compiler)
    kapt(libs.dagger.processor)
    implementation(libs.material)
    implementation(libs.play.core)
    implementation(libs.play.core.ktx)
    implementation(libs.ktor.negotiation)
    implementation(libs.ktor.core)
    implementation(libs.ktor.json)
    implementation(libs.ktor.cio)
    implementation(libs.insets)
    implementation(libs.glide)
    debugImplementation(libs.leakcanary)
    testImplementation(libs.junit)
    testImplementation(kotlin("test"))
    androidTestImplementation(libs.androidx.junit)
}

// cargo install cargo-ndk

val ndkApi = android.defaultConfig.minSdk
val nativeLibPath = "$projectDir/../native"

tasks.register<Exec>("buildRust") {
    group = "rust"
    val cargoPath = "${System.getProperty("user.home")}/.cargo/bin/cargo"
    workingDir(nativeLibPath)
    commandLine(
        cargoPath, "ndk",
        "-t", "arm64-v8a",
        "-t", "armeabi-v7a",
        "-t", "x86",
        "-t", "x86_64",
        "-P", "$ndkApi",
        "-o", "$projectDir/src/main/jniLibs",
        "build", "--release"
    ).apply {
        println("run if fails: cd $nativeLibPath && ${commandLine.joinToString(separator = " ")}\n")
    }
}

tasks.named("preBuild") {
    dependsOn("buildRust")
}

tasks.named("preBuild") {
    dependsOn("clean")
}


val targets = listOf(
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
)

val process = ProcessBuilder("rustup", "target", "add", *targets.toTypedArray())
    .redirectErrorStream(true)
    .start()!!
if (process.waitFor() != 0) {
    throw IllegalStateException(process.inputStream.bufferedReader().readText())
}

val os = OperatingSystem.current()!!
val host = when {
    os.isLinux -> "linux-x86_64"
    os.isMacOsX -> "darwin-x86_64"
    os.isWindows -> "windows-x86_64"
    else -> throw IllegalStateException("Unknown OS ($os)")
}

val ndkPath = android.sdkDirectory.resolve("ndk")
val ndkLlvmBin = "$ndkPath/${android.ndkVersion}/toolchains/llvm/prebuilt/$host/bin/"

val libConfigDir = File("$nativeLibPath/.cargo/")
libConfigDir.mkdirs()
File(libConfigDir, "config.toml").writeText(
"""# DON'T EDIT! Generated by $projectDir/build.gradle.kts

[target.aarch64-linux-android]
ar = "${ndkLlvmBin}aarch64-linux-android-ar"
linker = "${ndkLlvmBin}aarch64-linux-android$ndkApi-clang"

[target.armv7-linux-androideabi]
ar = "${ndkLlvmBin}arm-linux-androideabi-ar" # not 'armv7'
linker = "${ndkLlvmBin}armv7a-linux-androideabi$ndkApi-clang" # not 'armv7'

[target.x86_64-linux-android]
ar = "${ndkLlvmBin}x86_64-linux-android-ar"
linker = "${ndkLlvmBin}x86_64-linux-android$ndkApi-clang"

[target.i686-linux-android]
ar = "${ndkLlvmBin}i686-linux-android-ar"
linker = "${ndkLlvmBin}i686-linux-android$ndkApi-clang"
"""
)
